CREATE DATABASE PLANILLA
GO

USE PLANILLA
GO

CREATE TABLE EMPLEADOS(
ID_EMPLEADO INT IDENTITY CONSTRAINT PK_EMPLEADOS PRIMARY KEY NOT NULL,
CEDULA VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
PRIMER_APELLIDO VARCHAR(50) NOT NULL,
SEGUNDO_APELLIDO VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(20) NOT NULL,
CORREO VARCHAR(50) NULL,
NUMERO_CUENTA VARCHAR(50) NOT NULL,
FECHA_CONTRATACION DATE NOT NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE INFORMACION_ACADEMICA(
ID_INFORMACION_A INT CONSTRAINT PK_INFORMACION_ACADEMICA PRIMARY KEY NOT NULL,
ID_EMPLEADO INT NOT NULL,
GRADO VARCHAR(25) NOT NULL,
ESPECIALIDAD VARCHAR(100) NOT NULL,
INFORMACION VARCHAR(500) NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE PUESTOS(
ID_PUESTO INT IDENTITY CONSTRAINT PK_PUESTOS PRIMARY KEY NOT NULL,
NOMBRE_PUESTO VARCHAR(100) NOT NULL,
CATEGORIA_PUESTO INT NOT NULL,
SALARIO_BASE DECIMAL NOT NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE EMPLEADOS_PUESTOS(
ID_EMPLEADO_PUESTO INT IDENTITY CONSTRAINT PK_EMPLEADOS_PUESTOS PRIMARY KEY NOT NULL,
ID_EMPLEADO INT NOT NULL,
ID_PUESTO INT NOT NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE PLANILLAS(
ID_PLANILLA INT IDENTITY CONSTRAINT PK_PLANILLAS PRIMARY KEY NOT NULL,
FECHA DATE NOT NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE DETALLES_PLANILLAS(
ID_DETALLE_PLANILLA INT IDENTITY CONSTRAINT PK_DETALLES_PLANILLAS PRIMARY KEY NOT NULL,
ID_PLANILLA INT NOT NULL,
ID_EMPLEADO INT NOT NULL,
SALARIO_NETO DECIMAL NOT NULL,
SALARIO_BRUTO DECIMAL NOT NULL,
PRIMER_ADELANTO DECIMAL NOT NULL,
ADELANTO_FINAL_SALARIAL DECIMAL NOT NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE PAGOS(
ID_PAGO INT IDENTITY CONSTRAINT PK_PAGOS PRIMARY KEY NOT NULL,
ID_DETALLE_PLANILLA INT NOT NULL,
PORCENTAJE DECIMAL NULL,
MONTO DECIMAL NOT NULL
)

CREATE TABLE DEDUCCIONES(
ID_DEDUCCION INT IDENTITY CONSTRAINT PK_DEDUCCIONES PRIMARY KEY NOT NULL,
ID_DETALLE_PLANILLA INT NOT NULL,
PORCENTAJE DECIMAL NULL,
MONTO DECIMAL NOT NULL
)