CREATE DATABASE PLANILLA
GO

USE PLANILLA
GO

CREATE TABLE EMPLEADOS(
ID_EMPLEADO INT IDENTITY CONSTRAINT PK_EMPLEADOS PRIMARY KEY NOT NULL,
CEDULA VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(50) NOT NULL,
PRIMER_APELLIDO VARCHAR(50) NOT NULL,
SEGUNDO_APELLIDO VARCHAR(50) NOT NULL,
TELEFONO VARCHAR(20) NOT NULL,
CORREO VARCHAR(50) NULL,
NUMERO_CUENTA VARCHAR(50) NOT NULL,
FECHA_CONTRATACION DATE NOT NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE INFORMACION_ACADEMICA(
ID_INFORMACION_A INT CONSTRAINT PK_INFORMACION_ACADEMICA PRIMARY KEY NOT NULL,
ID_EMPLEADO INT NOT NULL,
GRADO VARCHAR(25) NOT NULL,
ESPECIALIDAD VARCHAR(100) NOT NULL,
INFORMACION VARCHAR(500) NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE PUESTOS(
ID_PUESTO INT IDENTITY CONSTRAINT PK_PUESTOS PRIMARY KEY NOT NULL,
NOMBRE_PUESTO VARCHAR(100) NOT NULL,
CATEGORIA_PUESTO INT NOT NULL,
SALARIO_BASE DECIMAL NOT NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE EMPLEADOS_PUESTOS(
ID_EMPLEADO_PUESTO INT IDENTITY CONSTRAINT PK_EMPLEADOS_PUESTOS PRIMARY KEY NOT NULL,
ID_EMPLEADO INT NOT NULL,
ID_PUESTO INT NOT NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE PLANILLAS(
ID_PLANILLA INT IDENTITY CONSTRAINT PK_PLANILLAS PRIMARY KEY NOT NULL,
FECHA DATE NOT NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE DETALLES_PLANILLAS(
ID_DETALLE_PLANILLA INT IDENTITY CONSTRAINT PK_DETALLES_PLANILLAS PRIMARY KEY NOT NULL,
ID_PLANILLA INT NOT NULL,
ID_EMPLEADO INT NOT NULL,
SALARIO_NETO DECIMAL NOT NULL,
SALARIO_BRUTO DECIMAL NOT NULL,
PRIMER_ADELANTO DECIMAL NOT NULL,
ADELANTO_FINAL_SALARIAL DECIMAL NOT NULL,
BORRADO_LOGICO BIT NOT NULL
)

CREATE TABLE PAGOS(
ID_PAGO INT IDENTITY CONSTRAINT PK_PAGOS PRIMARY KEY NOT NULL,
ID_DETALLE_PLANILLA INT NOT NULL,
PORCENTAJE DECIMAL NULL,
MONTO DECIMAL NOT NULL
)

CREATE TABLE DEDUCCIONES(
ID_DEDUCCION INT IDENTITY CONSTRAINT PK_DEDUCCIONES PRIMARY KEY NOT NULL,
ID_DETALLE_PLANILLA INT NOT NULL,
PORCENTAJE DECIMAL NULL,
MONTO DECIMAL NOT NULL
)

--******************************************************************************
--EMPLEADOS
GO
ALTER TABLE EMPLEADOS
ADD CONSTRAINT DF_BORRADO_LOGICO
DEFAULT 0 FOR BORRADO_LOGICO


--******************************************************************************
--INFORMACION_ACADEMICA
GO
ALTER TABLE INFORMACION_ACADEMICA
ADD CONSTRAINT FK_INFORMACION_ACADEMICA
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)

GO
ALTER TABLE INFORMACION_ACADEMICA
ADD CONSTRAINT CHK_INFORMACION_ACADEMICA
CHECK (GRADO IN('BACHILLER', 'LICENCIADO', 'MAESTRIA', 'DOCTORADO', 'TECNICO', 'OTRO'))

GO
ALTER TABLE INFORMACION_ACADEMICA
ADD CONSTRAINT DF_INFORMACION_ACADEMICA_BORRADO
DEFAULT 0 FOR BORRADO_LOGICO

--******************************************************************************
--PUESTOS
GO
ALTER TABLE PUESTOS
ADD CONSTRAINT DF_BORRADO_PUESTOS
DEFAULT 0 FOR BORRADO_LOGICO

--******************************************************************************
--EMPLEADOS_PUESTOS
GO 
ALTER TABLE EMPLEADOS_PUESTOS
ADD CONSTRAINT FK1_EMPLEADOS_PUESTOS
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)

GO
ALTER TABLE EMPLEADOS_PUESTOS
ADD CONSTRAINT FK2_EMPLEADOS_PUESTOS
FOREIGN KEY (ID_PUESTO) REFERENCES PUESTOS(ID_PUESTO)

GO
ALTER TABLE EMPLEADOS_PUESTOS
ADD CONSTRAINT DF_EMPLADOS_PUESTOS_BORRRADO
DEFAULT 0 FOR BORRADO_LOGICO

--******************************************************************************
--PLANILLAS

GO
ALTER TABLE PLANILLAS
ADD CONSTRAINT DF_BORRADO_PLANILLAS
DEFAULT 0 FOR BORRADO_LOGICO

--******************************************************************************
--DETALLES PLANILLAS

GO
ALTER TABLE DETALLES_PLANILLAS
ADD CONSTRAINT FK1_DETALLES_PLANILLAS
FOREIGN KEY (ID_PLANILLA) REFERENCES PLANILLAS(ID_PLANILLA)

GO
ALTER TABLE DETALLES_PLANILLAS
ADD CONSTRAINT FK2_DETALLES_PLANILLAS
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)

GO
ALTER TABLE DETALLES_PLANILLAS
ADD CONSTRAINT DF_DETALLES_PLANILLAS
DEFAULT 0 FOR BORRADO_LOGICO

--********************************************************************************
--PAGOS

GO
ALTER TABLE PAGOS
ADD CONSTRAINT FK_PAGOS
FOREIGN KEY (ID_DETALLE_PLANILLA) REFERENCES DETALLES_PLANILLAS(ID_DETALLE_PLANILLA)

--*********************************************************************************
--DEDUCCIONES
GO
ALTER TABLE DEDUCCIONES
ADD CONSTRAINT FK_DEDUCCIONES
FOREIGN KEY (ID_DETALLE_PLANILLA) REFERENCES DETALLES_PLANILLAS(ID_DETALLE_PLANILLA)

--DROP DATABASE PLANILLA

--/********************************************************************************/
--/                                                                                /
--/                            PROCEDOMIENTOS ALMACENADOS                          /
--/                                                                                /
--/********************************************************************************/

GO
CREATE PROCEDURE SP_GUARDAR_EMPLEADO(@id_empleado int out,
									 @cedula varchar(20),
									 @nombre varchar(50),
									 @primer_apellido varchar(50),
									 @segundo_apellido varchar(50),
									 @telefono varchar(20),
									 @correo varchar(50),
									 @numero_cuenta varchar(50),
									 @fecha_contratacion date,
									 @msj varchar(150) out)
AS
BEGIN TRY
	
ENTRY
BEGIN CATCH

END CATCH