/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Entidades.ClsPuestos;
import Entidades.ClsRetorno;
import Logica.ClsLogicaPuestos;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thomas Chevez
 */
public class FrmPuestos extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmPuestos
     */
    public FrmPuestos() {
        initComponents();
        this.closable = true;
        Limpiar();
        try {
            CargarListaRegistros();
        } catch (Exception e) {
        }
    }
    
    private void Limpiar() {
        txt_BuscarPuesto.setText("");
        txt_CategoriaPuesto.setText("");
        txt_NombrePuesto.setText("");
        txt_SalarioBase.setText("");
        txt_idPuesto.setText("-1");
        txt_idPuesto.setVisible(false);
    }
    
    private ClsPuestos LeerPuestos() {
        //Variables
        ClsPuestos vlo_Puestos = new ClsPuestos();

        //Inicio
        vlo_Puestos.setVgc_NombrePuesto(txt_NombrePuesto.getText());
        vlo_Puestos.setVgn_CategoriaPuesto(Integer.parseInt(txt_CategoriaPuesto.getText()));
        vlo_Puestos.setVgn_SalarioBase(Double.parseDouble(txt_SalarioBase.getText()));
        vlo_Puestos.setVgn_iPuesto(Integer.parseInt(txt_idPuesto.getText()));
        
        return vlo_Puestos;
    }
    
    private void CargarListaRegistros() throws Exception {
        //Variables
        ResultSet vlo_RS;
        ClsLogicaPuestos vlo_LogicaPuestos = new ClsLogicaPuestos();
        DefaultTableModel Modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        //Inicio
        tbl_Puestos.setModel(Modelo);
        Modelo.addColumn("Código");
        Modelo.addColumn("Puesto");
        Modelo.addColumn("Categoria");
        Modelo.addColumn("Salario Base");
        try {
            vlo_RS = vlo_LogicaPuestos.ListaPuestos(txt_BuscarPuesto.getText());
            Object[] fila = new Object[4];
            while (vlo_RS.next()) {
                for (int i = 0; i < 4; i++) {
                    fila[i] = vlo_RS.getObject(i + 1);
                }
                Modelo.addRow(fila);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar la lista de registros.");
            throw e;
        }
    }
    
    private ClsRetorno GuardarPuesto() throws Exception {
        //Variables
        ClsLogicaPuestos vlo_LogicaPuestos = new ClsLogicaPuestos();
        ClsRetorno vlo_Retorno = new ClsRetorno();

        //Inicio
        try {
            vlo_Retorno = vlo_LogicaPuestos.GuardarPuesto(LeerPuestos());
        } catch (Exception e) {
            throw e;
        }
        Limpiar();
        return vlo_Retorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_NombrePuesto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_CategoriaPuesto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_SalarioBase = new javax.swing.JTextField();
        btn_Guardar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Puestos = new javax.swing.JTable();
        txt_BuscarPuesto = new javax.swing.JTextField();
        btn_Buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JButton();
        txt_idPuesto = new javax.swing.JTextField();

        setTitle("Puestos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Guardar Puesto"));

        jLabel1.setText("Nombre del Puesto:");

        txt_NombrePuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombrePuestoKeyTyped(evt);
            }
        });

        jLabel2.setText("Categoria Puesto:");

        txt_CategoriaPuesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CategoriaPuestoKeyTyped(evt);
            }
        });

        jLabel3.setText("Salario Base:");

        txt_SalarioBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_SalarioBaseKeyTyped(evt);
            }
        });

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_SalarioBase)
                    .addComponent(txt_NombrePuesto)
                    .addComponent(txt_CategoriaPuesto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Guardar)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NombrePuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_CategoriaPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_SalarioBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guardar)
                    .addComponent(btn_Eliminar)
                    .addComponent(btnLimpiar)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Puestos"));

        tbl_Puestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_Puestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_PuestosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Puestos);

        btn_Buscar.setText("Buscar");
        btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre del puesto:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_BuscarPuesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Buscar))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_BuscarPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Buscar)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txt_idPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 542, Short.MAX_VALUE)
                        .addComponent(btn_Salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Salir)
                    .addComponent(txt_idPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NombrePuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombrePuestoKeyTyped
        if (txt_NombrePuesto.getText().length() == 100) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_NombrePuestoKeyTyped

    private void txt_CategoriaPuestoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CategoriaPuestoKeyTyped
        char e = evt.getKeyChar();
        if (!(e >= '0' && e <= '9')) {
            evt.consume();
        }
        if (txt_CategoriaPuesto.getText().length() == 2) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_CategoriaPuestoKeyTyped

    private void txt_SalarioBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SalarioBaseKeyTyped
        char e = evt.getKeyChar();
        if (!(e >= '0' && e <= '9')) {
            evt.consume();
        }
        if (txt_SalarioBase.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_SalarioBaseKeyTyped

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        //Varaibles
        ClsRetorno vlo_returno = new ClsRetorno();

        //Inicio
        if (txt_CategoriaPuesto.getText().equals("") || txt_NombrePuesto.getText().equals("") || txt_SalarioBase.getText().equals("") || txt_idPuesto.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Error no se puede ingresar puesto falta un campo requerido.");
        } else {
            try {
                vlo_returno = GuardarPuesto();
                JOptionPane.showMessageDialog(this, vlo_returno.getVgc_Mensaje());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarActionPerformed
        try {
            CargarListaRegistros();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_BuscarActionPerformed

    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        //Variables
        ClsLogicaPuestos vlo_LogicaPuestos = new ClsLogicaPuestos();
        ClsRetorno vloRetorno = new ClsRetorno();

        //Inicio
        try {
            vloRetorno = vlo_LogicaPuestos.EliminarPuesto(Integer.parseInt(txt_idPuesto.getText()));
            JOptionPane.showMessageDialog(this, vloRetorno.getVgc_Mensaje());
            CargarListaRegistros();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        Limpiar();
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void tbl_PuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_PuestosMouseClicked
        //Variables
        ClsPuestos vlo_Puestos = new ClsPuestos();
        ClsLogicaPuestos vlo_LogicaPuestos = new ClsLogicaPuestos();

        //Inicio
        if (evt.getClickCount() == 2) {
            try {
                vlo_Puestos = vlo_LogicaPuestos.ObtenerPuesto(Integer.parseInt(tbl_Puestos.getValueAt(tbl_Puestos.getSelectedRow(), 0).toString()));
                txt_CategoriaPuesto.setText(Integer.toString(vlo_Puestos.getVgn_CategoriaPuesto()));
                txt_NombrePuesto.setText(vlo_Puestos.getVgc_NombrePuesto());
                txt_SalarioBase.setText(Double.toString(vlo_Puestos.getVgn_SalarioBase()));
                txt_idPuesto.setText(Integer.toString(vlo_Puestos.getVgn_iPuesto()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar el puesto seleccionado.");
            }
        }
    }//GEN-LAST:event_tbl_PuestosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btn_Buscar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Puestos;
    private javax.swing.JTextField txt_BuscarPuesto;
    private javax.swing.JTextField txt_CategoriaPuesto;
    private javax.swing.JTextField txt_NombrePuesto;
    private javax.swing.JTextField txt_SalarioBase;
    private javax.swing.JTextField txt_idPuesto;
    // End of variables declaration//GEN-END:variables
}
